export const GOT_TOKEN = 'GOT_TOKEN'
export const GOT_CUSTOMERS_COUNT = 'GOT_CUSTOMERS_COUNT';
export const GOT_CUSTOMERS = 'GOT_CUSTOMERS';
export const GOT_CUSTOMER = 'GOT_CUSTOMER';
export const CUSTOMER_CREATED = 'CUSTOMER_CREATED';
export const CUSTOMER_UPDATED = 'CUSTOMER_UPDATED';
export const CUSTOMER_DELETED = 'CUSTOMER_DELETED';